### ISSUE TITLE
🧩FEATURE REQUEST: Add lazy image loading to improve optimization

### ISSUE THREAD

**Issue by esau-morais** [rutikwankhade/devspace#2]
### Expected behaviour

It'd be great to load the images using the blur effect and improve the web app optimization

### Actual behaviour

In the actual web app version, the images still loading with the default type.

### Solution

Use the `loading` statement variable to the images and provide a blur CSS filter with the `filter` property

**Comment by rutikwankhade** [comment]
That sounds great. It will improve the UX  a lot. 👍 Thanks for sharing. 
Would you like to contribute and work on this issue?

**Comment by esau-morais** [comment]
Sure, it'll be great 🤩

I'd like just to know before: Can I format your code and also remove the unnecessary imports? It'd be great to add Prettier and keep a pattern to the formatting

Also, I see that there's already a "loader" component, so it'd better if I replace it or just keep it (closing the issue)

**Comment by rutikwankhade** [comment]
Yeh, sure. go ahead.
